version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "senha"
      POSTGRES_USER: "user"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes:/var/lib/postgresql/data
    networks:
      - brnet

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - brnet

networks:
  brnet:
    driver: bridge
