version: '3.8'

services:
  ui:
    build: ./ui
    ports:
      - "80:1234"
    depends_on:
      - transactionservice
    networks:
      - brnet

  transporterservice:
    build: ./web-transporters
    ports: 
      - "9001:9001"
    networks:
      - brnet

  transactionservice:
    build: ./web-transactions
    depends_on:
      - transactiondb
      - transporterservice
    ports:
      - "9000:9000"
    networks:
      - brnet
  transactiondb:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "senha"
      POSTGRES_USER: "user"
      POSTGRES_DB: "sms"
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes:/var/lib/postgresql/data
    networks:
      - brnet
networks:
  brnet:
    driver: bridge
