version: '3.8'

services:
  ui:
    build: ./ui
    ports:
      - "80:80"
    depends_on:
      - accountservice
    networks:
      - brnet

  transporterservice:
    build: ./web-transporters
    ports: 
      - "9001:9001"
    networks:
      - brnet

  accountservice:
    build: ./web-account
    ports:
      - "9000:9000"
    depends_on:
      - accountdb
      - transporterservice
    networks:
      - brnet
  accountdb:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "senha"
      POSTGRES_USER: "user"
      POSTGRES_DB: "smsaccounts"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes:/var/lib/postgresql/data
    networks:
      - brnet
  # transactionservice:
  #   build: ./web-transaction
  # transactiondb:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_PASSWORD: "senha"
  #     POSTGRES_USER: "user"
  #     POSTGRES_DB: "sms"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./volumes:/var/lib/postgresql/data
  #   networks:
  #     - brnet
  
  # productservice:
  #   build: ./web-product
  # productdb:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_PASSWORD: "senha"
  #     POSTGRES_USER: "user"
  #     POSTGRES_DB: "sms"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./volumes:/var/lib/postgresql/data
  #   networks:
  #     - brnet
networks:
  brnet:
    driver: bridge
