version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "senha"
      POSTGRES_USER: "user"
      POSTGRES_DB: "sms"
    ports:
      - "5432:5432"
    volumes:
      - ./volumes:/var/lib/postgresql/data
    networks:
      - brnet
  
  # accountservice:
  #   build: ./web-account
  # accountdb:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_PASSWORD: "senha"
  #     POSTGRES_USER: "user"
  #     POSTGRES_DB: "sms"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./volumes:/var/lib/postgresql/data
  #   networks:
  #     - brnet
  
  # transactionservice:
  #   build: ./web-transaction
  # transactiondb:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_PASSWORD: "senha"
  #     POSTGRES_USER: "user"
  #     POSTGRES_DB: "sms"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./volumes:/var/lib/postgresql/data
  #   networks:
  #     - brnet
  
  # productservice:
  #   build: ./web-product
  # productdb:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_PASSWORD: "senha"
  #     POSTGRES_USER: "user"
  #     POSTGRES_DB: "sms"
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./volumes:/var/lib/postgresql/data
  #   networks:
  #     - brnet
networks:
  brnet:
    driver: bridge